### ISSUE TITLE
Epic: Basic contract inspection

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/ganache#303]
Ganache transactions should display information relevant to the user's contracts.

Task list (will likely break this up into multiple issues):

- [ ] Add ability to import truffle build artifacts
- [ ] Display solidity function called by transaction
- [ ] Display solidity function arguments 
- [ ] Display runtime errors
- [ ] Display basic storage variable updates (e.g. not maps or arrays)
- [ ] Display storage array updates
- [ ] Display storage map updates

**Comment by benjamincburns** [comment]
Closing this in favor of trufflesuite/roadmap#77
